### PR TITLE
Fix thread safety in getRemainingStock

### LINKED ISSUE #2294: [BUG] /qs clean doesnt'work in folia sometimes
### Description

https://mclo.gs/iIfrnkc

### Steps to reproduce

1. use /qs clean in folia
2. something will throw error It is akin to a matter of probability.

### Expected Behaviour

nothing error

### Screenshots

_No response_

### `/quickshop paste` URL

default

### Additional Context

_No response_

### Checklist

- [ ] I'm running Paper, and not a fork
- [ ] I confirm that Paper has been updated to the latest build
- [x] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [x] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [x] I confirm that I am running a server that is not a Hybrid Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a NeoForge/Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [x] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

### PR DESCRIPTION
**Pull request by wling-art**
# Type of Change

Please select the type of change this PR represents:

- [ ] feat – New feature
- [x] fix – Bug fix
- [ ] hotfix – Urgent production fix
- [ ] refactor – Code improvement (no behavior change)
- [ ] docs – Documentation/config comment changes only
- [ ] chore – Build/tooling/internal maintenance
- [ ] breaking – Breaking change (requires migration)

> If this is a breaking change, clearly describe the migration steps below.

---

# General Contribution Checklist

- [x] I have read and understood the [CONTRIBUTING.md](.contributing/contributing.md).
- [x] My branch name follows the naming conventions in CONTRIBUTING.md.
- [x] I have signed the Contributor License Agreement (CLA), if required.
- [x] My changes are based on the latest `hikari` branch.
- [x] I have tested my changes locally.
- [x] Existing functionality has not been unintentionally broken.

---

# Description of Changes

Fix thread safety in getRemainingStock by scheduling inventory access on correct region.

fix #2294

### CODE REVIEW

File: quickshop-bukkit/src/main/java/com/ghostchu/quickshop/shop/ContainerShop.java [hunk 1]
```diff
@@ -686,20 +686,39 @@ public int getRemainingSpace() {
   @Override
   public int getRemainingStock() {
 
-    if(this.unlimited) {
+    if (this.unlimited) {
```
Comment (creatorfromhell) [inline quickshop-bukkit/src/main/java/com/ghostchu/quickshop/shop/ContainerShop.java]: Style guideline fixes, space between if and parentheses. https://github.com/QuickShop-Community/QuickShop-Hikari/blob/2c841250313c74e688f5da10e745cb31d83e110f/.contributing/QuickShop_Style.xml#L34

File: quickshop-bukkit/src/main/java/com/ghostchu/quickshop/shop/ContainerShop.java [hunk 2]
```diff
@@ -686,20 +686,39 @@ public int getRemainingSpace() {
...
       return -1;
     }
-    if(Bukkit.isPrimaryThread()) {
-      if(this.getInventory() == null) {
-        Log.debug("Failed to calc RemainingStock for shop " + this + ": Inventory null.");
+
+    if (Bukkit.getServer().isOwnedByCurrentRegion(location)) {
```
Comment (creatorfromhell) [inline quickshop-bukkit/src/main/java/com/ghostchu/quickshop/shop/ContainerShop.java]: Style guideline fixes, space between if and parentheses. https://github.com/QuickShop-Community/QuickShop-Hikari/blob/2c841250313c74e688f5da10e745cb31d83e110f/.contributing/QuickShop_Style.xml#L34

File: quickshop-bukkit/src/main/java/com/ghostchu/quickshop/shop/ContainerShop.java [hunk 3]
```diff
@@ -686,20 +686,39 @@ public int getRemainingSpace() {
...
+
+      if (this.getInventory() == null) {
```
Comment (creatorfromhell) [inline quickshop-bukkit/src/main/java/com/ghostchu/quickshop/shop/ContainerShop.java]: Style guideline fixes, space between if and parentheses. https://github.com/QuickShop-Community/QuickShop-Hikari/blob/2c841250313c74e688f5da10e745cb31d83e110f/.contributing/QuickShop_Style.xml#L34

File: quickshop-bukkit/src/main/java/com/ghostchu/quickshop/shop/ContainerShop.java [hunk 4]
```diff
@@ -686,20 +686,39 @@ public int getRemainingSpace() {
...
         return 0;
       }
       final int stock = Util.countItems(this.getInventory(), this);
       new ShopInventoryCalculateEvent(this, -1, stock).callEvent();
       return stock;
-    } else {
-      return plugin.getShopManager().queryShopInventoryCacheInDatabase(this).join().getStock();
     }
+
+    CompletableFuture<Integer> future = new CompletableFuture<>();
```
Comment (creatorfromhell) [inline quickshop-bukkit/src/main/java/com/ghostchu/quickshop/shop/ContainerShop.java]: Does this need to be modified elsewhere, or can it be notated as final?

File: quickshop-bukkit/src/main/java/com/ghostchu/quickshop/shop/ContainerShop.java [hunk 5]
```diff
@@ -686,20 +686,39 @@ public int getRemainingSpace() {
...
+
+    QuickShop.folia()
+        .getScheduler()
+        .runAtLocation(
+            this.location,
+            task -> {
+              if (this.getInventory() == null) {
```
Comment (creatorfromhell) [inline quickshop-bukkit/src/main/java/com/ghostchu/quickshop/shop/ContainerShop.java]: Style guideline fixes, space between if and parentheses. https://github.com/QuickShop-Community/QuickShop-Hikari/blob/2c841250313c74e688f5da10e745cb31d83e110f/.contributing/QuickShop_Style.xml#L34

**Review by creatorfromhell — CHANGES_REQUESTED** [review]

**Review by creatorfromhell — APPROVED** [review]
